<a href="https://colab.research.google.com/github/Arjun-coder5/Machine-Learning/blob/main/Numpy_01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NumPy - Numerical Python :

 **Advantages  of  Numpy**  -

 1.Allow Sevelar Mathmatical Operations

 2.Faster operations.

List vs Numpy - time taken :

In [46]:
from time import process_time

Time taken by a list :

In [47]:
python_list  = [i for i in range(100)]

start_time = process_time()
python_list = [i+5 for i in python_list]

end_time = process_time()
print(end_time-start_time)

0.0001554039999973611


Tine taken by a list :

In [48]:
import numpy as np

In [49]:
np_arr = np.array([i for i in range(100)])

start_time = process_time()
np_arr += 5  # np_arr = np_arry + 5
end_time = process_time()
print(end_time-start_time)


0.00011302700000115351


Numpy array


In [50]:
#list
list1 = [1,2,3,4,5]
print(list1)
type(list1)

[1, 2, 3, 4, 5]


list

In [51]:
import numpy as np

In [52]:
my_arr = np.array([1, 2, 3])
print(my_arr[0]) # Returns 1


1


Creating 1d array -

In [53]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [54]:
a.shape

(4,)

In [55]:
b = np.array([(1,2,3,4),(5,6,7,8)])
print(b)
b.shape

[[1 2 3 4]
 [5 6 7 8]]


(2, 4)

In [56]:
c = np.array([(1,2,3,4),(5,6,7,8)],dtype=float)
print(c)

[[1. 2. 3. 4.]
 [5. 6. 7. 8.]]


Initial PlaceHolde in numpy array :

In [57]:
#create a numpy array of zeroes :
x = np.zeros((4,5))
print(x)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [58]:
# create a numppy rray of oones :
y = np.ones((3,3))
print(y)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [59]:
#arr of a perticacular value :
z = np.full((5,4),5)
print(z)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [60]:
# create an identity matrics :
k = np.eye(5)
print(k)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [61]:
# create a numppy array with random values :
b = np.random.random((3,4))
print(b)

[[0.57066138 0.76255581 0.85347001 0.51914563]
 [0.45427682 0.36674941 0.55641765 0.15943216]
 [0.10455224 0.9778065  0.59386344 0.91821294]]


In [62]:
# create a numpy array with random integer not from 0 to 1 only :
p = np.random.randint(10,100,(3,5))
print(p)

[[75 68 55 28 62]
 [62 66 93 54 37]
 [43 10 36 89 83]]


In [63]:
# array of evenly spaced value : specifying the vunber of values we want :
d = np.linspace(10,30,6)
print(d)

[10. 14. 18. 22. 26. 30.]


In [75]:
pip install --upgrade numpy

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16.6/16.6 MB 70.0 MB/s eta 0:00:00
  Attempting uninstall: numpy
    Found existing installation: numpy 2.0.2
    Uninstalling numpy-2.0.2:
      Successfully uninstalled numpy-2.0.2
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
tensorflow 2.19.0 requires numpy<2.2.0,>=1.26.0, but you have numpy 2.4.2 which is incompatible.
numba 0.60.0 requires numpy<2.1,>=1.22, but you have numpy 2.4.2 which is incompatible.


In [64]:
# array of evenly spaced values : speciing the step :
e =  np.arange(10,30,5)
print(e)


[10 15 20 25]


In [65]:
# convert a list to a numpy array :
list2 = [10,20,30,40,50]

np_ar = np.asarray(list2)
print(np_ar)
type(np_ar)

[10 20 30 40 50]


numpy.ndarray

Analysing anumpy array :

In [66]:
c = np.random.randint(10,90,(3,4))
print(c)

[[64 34 14 44]
 [23 56 40 62]
 [42 75 82 51]]


In [67]:
# ARRAY DIMENSION :
print(c.shape)

(3, 4)


In [68]:
# Th e number of dimension :
print(c.ndim)

2


In [69]:
# number of elements in the array :
print(c.size)

12


In [70]:
# checking the data type of values in the array :
print(c.dtype)

int64


Mathmatical operation numpy rray :

In [71]:
list1 = [1,2,3,4,5]
list2 = [6,7,8,9,10]
print(list1+list2) # concatenate or joins two list

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [72]:
a = np.random.randint(10,30,(3,3))
b = np.random.randint(10,30,(3,3))
print(a)
print(b)

[[13 24 21]
 [21 14 26]
 [13 21 19]]
[[24 15 26]
 [13 13 12]
 [16 17 19]]


In [73]:
print(a+b)
print(a-b)
print(a*b)
print(a/b)

[[37 39 47]
 [34 27 38]
 [29 38 38]]
[[-11   9  -5]
 [  8   1  14]
 [ -3   4   0]]
[[312 360 546]
 [273 182 312]
 [208 357 361]]
[[0.54166667 1.6        0.80769231]
 [1.61538462 1.07692308 2.16666667]
 [0.8125     1.23529412 1.        ]]


In [74]:
print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))

[[37 39 47]
 [34 27 38]
 [29 38 38]]
[[-11   9  -5]
 [  8   1  14]
 [ -3   4   0]]
[[312 360 546]
 [273 182 312]
 [208 357 361]]
